MACRO(ADD_CATALYST_DEPENDENCY target)
	IF(ParaView_FOUND)
		INCLUDE("${PARAVIEW_USE_FILE}")

		# see http://stackoverflow.com/questions/18642155
		SET_PROPERTY(TARGET ${target} APPEND PROPERTY COMPILE_DEFINITIONS ${VTK_DEFINITIONS})
	ENDIF()

	IF(TARGET VtkRescan)
		ADD_DEPENDENCIES(${target} VtkRescan)
	ENDIF()
ENDMACRO()
