# Set additional CMake modules path
SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH}
  "${CMAKE_CURRENT_SOURCE_DIR}/scripts/cmake/cmake"
  "${CMAKE_CURRENT_SOURCE_DIR}/scripts/cmake")

# Load addional modules
INCLUDE(UseBackportedModules)
INCLUDE(OptionRequires)
INCLUDE(CppcheckTargets)
INCLUDE(GetCompilerInfoString)
INCLUDE(AddCatalystDependency)

INCLUDE(ProcessorCount)
ProcessorCount(NUM_PROCESSORS)
SET(NUM_PROCESSORS ${NUM_PROCESSORS} CACHE STRING "Processor count")

INCLUDE(GetGitRevisionDescription)
GET_GIT_HEAD_REVISION(GIT_REFSPEC GIT_SHA1)
STRING(SUBSTRING ${GIT_SHA1} 0 8 GIT_SHA1_SHORT)

# Get the hostname
SITE_NAME(HOSTNAME)

# Compute OS X version number
IF(APPLE)
	IF(CMAKE_SYSTEM_VERSION VERSION_EQUAL 12.0)
		SET(OSX_VERSION 10.8 CACHE STRING "OS X version number")
		SET(OSX_VERSION_NAME CACHE STRING "Mountain Lion")
	ENDIF()
	IF(CMAKE_SYSTEM_VERSION VERSION_EQUAL 13.0)
		SET(OSX_VERSION 10.9 CACHE STRING "OS X version number")
		SET(OSX_VERSION_NAME CACHE STRING "Mavericks")
	ENDIF()
	IF(CMAKE_SYSTEM_VERSION VERSION_EQUAL 14.0)
		SET(OSX_VERSION 10.10 CACHE STRING "OS X version number")
		SET(OSX_VERSION_NAME CACHE STRING "Yosemite")
	ENDIF()
ENDIF()
MARK_AS_ADVANCED(OSX_VERSION OSX_VERSION_NAME)
