# Set additional CMake modules path
SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH}
  "${CMAKE_CURRENT_SOURCE_DIR}/scripts/cmake/cmake"
  "${CMAKE_CURRENT_SOURCE_DIR}/scripts/cmake")

# Load addional modules
INCLUDE(UseBackportedModules)
INCLUDE(OptionRequires)
INCLUDE(CppcheckTargets)
INCLUDE(GetCompilerInfoString)
INCLUDE(AddCatalystDependency)

INCLUDE(ProcessorCount)
ProcessorCount(NUM_PROCESSORS)
SET(NUM_PROCESSORS ${NUM_PROCESSORS} CACHE STRING "Processor count")

INCLUDE(GetGitRevisionDescription)
GET_GIT_HEAD_REVISION(GIT_REFSPEC GIT_SHA1)
STRING(SUBSTRING ${GIT_SHA1} 0 8 GIT_SHA1_SHORT)
GIT_GET_TAG(GIT_DESCRIBE)

STRING(REGEX MATCH ^[0-9|\\.]* GIT_TAG ${GIT_DESCRIBE})
SET(OGS_VERSION ${GIT_TAG})
IF(GIT_DESCRIBE MATCHES ".*-.*-.*")
	# Commit is not a tag
	SET(OGS_IS_RELEASE FALSE)
	STRING(REGEX MATCH "-([0-9]+)-" GIT_COMMITS_AFTER_TAG ${GIT_DESCRIBE})
ELSE()
	SET(OGS_VERSION_STATUS "")
	SET(OGS_IS_RELEASE TRUE)
	MESSAGE(STATUS "OGS version: ${OGS_VERSION}")
ENDIF()

# Get the hostname
SITE_NAME(HOSTNAME)

# Compute OS X version number
IF(APPLE)
	IF(CMAKE_SYSTEM_VERSION VERSION_EQUAL 12.0)
		SET(OSX_VERSION 10.8 CACHE STRING "OS X version number")
		SET(OSX_VERSION_NAME CACHE STRING "Mountain Lion")
	ENDIF()
	IF(CMAKE_SYSTEM_VERSION VERSION_EQUAL 13.0)
		SET(OSX_VERSION 10.9 CACHE STRING "OS X version number")
		SET(OSX_VERSION_NAME CACHE STRING "Mavericks")
	ENDIF()
	IF(CMAKE_SYSTEM_VERSION VERSION_EQUAL 14.0)
		SET(OSX_VERSION 10.10 CACHE STRING "OS X version number")
		SET(OSX_VERSION_NAME CACHE STRING "Yosemite")
	ENDIF()
ENDIF()
MARK_AS_ADVANCED(OSX_VERSION OSX_VERSION_NAME)
