if(DOXYGEN_FOUND)

	if(APPLE)
		option(DOCS_GENERATE_DOCSET "Generate Apple Docsets." OFF)
	endif()

	set(DOT_FOUND "NO")
	if(DOXYGEN_DOT_FOUND)
		set(DOT_FOUND "YES")
	endif()

	add_custom_target(doc ${DOXYGEN_EXECUTABLE} ${PROJECT_BINARY_DIR}/Doxyfile
		WORKING_DIRECTORY ${PROJECT_BINARY_DIR}
		COMMENT "Generating source code documentation with Doxygen." VERBATIM)

	set(DOCS_GENERATE_TREEVIEW_STRING "YES" CACHE INTERNAL "")
	set(DOCS_DISABLE_INDEX_STRING "NO" CACHE INTERNAL "")
	if(DOCS_GENERATE_DOCSET)
		set(DOCS_GENERATE_TREEVIEW_STRING "NO" CACHE INTERNAL "" FORCE)
		set(DOCS_DISABLE_INDEX_STRING "YES" CACHE INTERNAL "" FORCE)
		set(DOCS_GENERATE_DOCSET_STRING "YES" CACHE INTERNAL "")
		add_custom_command(TARGET doc POST_BUILD
			COMMAND make WORKING_DIRECTORY ${PROJECT_BINARY_DIR}/docs
			COMMENT "Generating docset ...")
	endif() # DOCS_GENERATE_DOCSET

	configure_file(Documentation/Doxyfile.in ${PROJECT_BINARY_DIR}/Doxyfile)

endif() # DOXYGEN_FOUND
