# cmake-lint: disable=C0103

# Appends source files (*.cpp), public header files (*.h) and private header
# files (*-impl.h).
# Signature:
#   append_source_and_header_files(source_files header_files
#                                  private_header_files
#                                  DIRECTORIES dir1 [dir2 ...])
function(append_source_and_header_files
         source_files
         header_files
         private_header_files
)
    cmake_parse_arguments(_ashf "" "" "DIRECTORIES" ${ARGN})

    if(_ashf_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR
            "append_source_and_header_files: unexpected arguments: "
            "${_ashf_UNPARSED_ARGUMENTS}"
        )
    endif()
    if(NOT _ashf_DIRECTORIES)
        message(FATAL_ERROR
            "append_source_and_header_files: DIRECTORIES requires at least "
            "one directory."
        )
    endif()
    set(_dirs ${_ashf_DIRECTORIES})

    set(_init_property "_OGS_ASHF_INITIALISED_${source_files}_${header_files}")
    get_property(_already_initialised DIRECTORY PROPERTY "${_init_property}")

    if(NOT _already_initialised)
        set_property(DIRECTORY PROPERTY "${_init_property}" TRUE)
        set(_appended_sources)
        set(_appended_headers)
        set(_appended_private_headers)
    else()
        set(_appended_sources ${${source_files}})
        set(_appended_headers ${${header_files}})
        set(_appended_private_headers ${${private_header_files}})
    endif()

    foreach(_dir IN LISTS _dirs)
        file(
            GLOB _dir_sources
            RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
            CONFIGURE_DEPENDS ${_dir}/*.cpp
        )
        file(
            GLOB _dir_all_headers
            RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}
            CONFIGURE_DEPENDS ${_dir}/*.h
        )

        set(_dir_headers ${_dir_all_headers})
        list(FILTER _dir_headers EXCLUDE REGEX ".*-impl\\.h$")

        set(_dir_private_headers ${_dir_all_headers})
        list(FILTER _dir_private_headers INCLUDE REGEX ".*-impl\\.h$")

        list(LENGTH _dir_sources _num_source_files)
        list(LENGTH _dir_headers _num_header_files)
        list(LENGTH _dir_private_headers _num_private_header_files)
        math(
            EXPR _num_files
            "${_num_source_files}+${_num_header_files}+${_num_private_header_files}"
        )
        if(_num_files EQUAL 0)
            message(FATAL_ERROR
                "No source or header files found in ${_dir}"
            )
        endif()

        list(APPEND _appended_sources ${_dir_sources})
        list(APPEND _appended_headers ${_dir_headers})
        list(APPEND _appended_private_headers ${_dir_private_headers})
    endforeach()

    list(REMOVE_DUPLICATES _appended_sources)
    list(REMOVE_DUPLICATES _appended_headers)
    set(${source_files} ${_appended_sources} PARENT_SCOPE)
    set(${header_files} ${_appended_headers} PARENT_SCOPE)

    list(REMOVE_DUPLICATES _appended_private_headers)
    set(${private_header_files}
        ${_appended_private_headers}
        PARENT_SCOPE
    )
endfunction()

# Adds the include dir containing the autogenerated files to the PUBLIC
# interface of the given target
function(add_autogen_include target)
    get_property(IsMultiConfig GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)
    if(IsMultiConfig)
        target_include_directories(
            ${target}
            PUBLIC
                ${CMAKE_CURRENT_BINARY_DIR}/${target}_autogen/include_$<CONFIG>
        )
    else()
        target_include_directories(
            ${target}
            PUBLIC ${CMAKE_CURRENT_BINARY_DIR}/${target}_autogen/include
        )
    endif()
endfunction()

# Replacement for add_library() for ogs libraries
function(ogs_add_library targetName)
    set(options STATIC SHARED GENERATE_EXPORT_HEADER)
    set(multiValueArgs SOURCES PUBLIC_HEADERS PRIVATE_HEADERS)
    cmake_parse_arguments(
        ogs_add_library
        "${options}"
        ""
        "${multiValueArgs}"
        ${ARGN}
    )

    foreach(file ${ogs_add_library_UNPARSED_ARGUMENTS})
        get_filename_component(file_path ${file} REALPATH)
        list(APPEND files ${file_path})
    endforeach()

    set(type "") # somehow type may be set to MODULE_LIBRARY from outside, bug?
    if(ogs_add_library_STATIC)
        set(type STATIC)
    elseif(ogs_add_library_SHARED)
        set(type SHARED)
    endif()
    add_library(${targetName} ${type} ${files})

    if(ogs_add_library_PUBLIC_HEADERS)
        target_sources(
            ${targetName}
            PUBLIC
                FILE_SET HEADERS
                # OGS convention is to include with path, e.g. BaseLib/MPI.h
                # Therefore overriding the default CMAKE_CURRENT_SOURCE_DIR
                # which may lead to e.g. #include <mpi.h> to be shadowed by
                # BaseLib/MPI.h on macOS (case-insensitive), same with
                # process.h on Windows.
                BASE_DIRS ${PROJECT_SOURCE_DIR}
                FILES ${ogs_add_library_PUBLIC_HEADERS}
        )
    endif()
    if(ogs_add_library_PRIVATE_HEADERS)
        target_sources(
            ${targetName}
            PRIVATE
                FILE_SET private_headers
                TYPE HEADERS
                BASE_DIRS ${PROJECT_SOURCE_DIR}
                FILES ${ogs_add_library_PRIVATE_HEADERS}
        )
    endif()

    target_compile_options(
        ${targetName}
        PRIVATE $<$<CXX_COMPILER_ID:Clang,AppleClang,GNU>:-Wall -Wextra
                -Wunreachable-code> $<$<CXX_COMPILER_ID:MSVC>:/W3>
    )

    if(BUILD_SHARED_LIBS AND NOT "${type}" STREQUAL "STATIC")
        install(TARGETS ${targetName}
                RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
                LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
        )
    endif()

    if(ogs_add_library_GENERATE_EXPORT_HEADER)
        include(GenerateExportHeader)
        generate_export_header(${targetName})
        string(TOLOWER "${targetName}" _targetName_lower)
        target_sources(${targetName}
            PUBLIC
                FILE_SET HEADERS
                BASE_DIRS
                    ${PROJECT_SOURCE_DIR}
                    ${CMAKE_CURRENT_BINARY_DIR}
                FILES ${CMAKE_CURRENT_BINARY_DIR}/${_targetName_lower}_export.h)
    endif()

    set_target_properties(
        ${targetName} PROPERTIES
            UNITY_BUILD ${OGS_USE_UNITY_BUILDS}
            VERIFY_INTERFACE_HEADER_SETS ON
    )

    if(OGS_INCLUDE_WHAT_YOU_USE)
        if(${CMAKE_CXX_COMPILER_ID} MATCHES ".*Clang")
            set_target_properties(
                ${targetName} PROPERTIES CXX_INCLUDE_WHAT_YOU_USE
                                         include-what-you-use
            )
        else()
            message(
                FATAL_ERROR
                    "OGS_INCLUDE_WHAT_YOU_USE requires the clang compiler!"
            )
        endif()
    endif()

    if(MSVC)
        GroupSourcesByFolder(${targetName})
    endif()
endfunction()

set(_OGS_EXECUTABLES "" CACHE INTERNAL "")

# Replacement for ogs_add_executable() for ogs executables
function(ogs_add_executable targetName)
    cmake_parse_arguments(ogs_add_executable "" "" "" ${ARGN})

    foreach(file ${ogs_add_executable_UNPARSED_ARGUMENTS})
        get_filename_component(file_path ${file} REALPATH)
        list(APPEND files ${file_path})
    endforeach()

    if(WIN32)
        # Generate manifest file with long paths enabled. Is added to source
        # files which embeds it into the executable. To work long paths have
        # to be enabled in the registry as well:
        # https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later
        set(target_mn_filename "${targetName}_longpath.manifest")
        set(mn_file_output "${CMAKE_CURRENT_BINARY_DIR}/${target_mn_filename}")

        set(mn_contents [=[<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
<application  xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
        <ws2:longPathAware>true</ws2:longPathAware>
    </windowsSettings>
</application>
</assembly>]=])
        file(GENERATE OUTPUT "${mn_file_output}" CONTENT "${mn_contents}")
        list(APPEND files ${mn_file_output})
    endif()

    add_executable(${targetName} ${files})

    target_compile_options(
        ${targetName}
        PRIVATE $<$<CXX_COMPILER_ID:Clang,AppleClang,GNU>:-Wall -Wextra
                -Wunreachable-code> $<$<CXX_COMPILER_ID:MSVC>:/W3>
    )

    # Add project root to include directories for cross-library includes
    target_include_directories(${targetName} PRIVATE ${PROJECT_SOURCE_DIR})

    set(ogs_executables "${_OGS_EXECUTABLES}")
    list(APPEND ogs_executables "${targetName}")
    set(_OGS_EXECUTABLES "${ogs_executables}" CACHE INTERNAL "list of exes")
endfunction()

# Parses current directory into a list
function(current_dir_as_list baseDir outList)
    file(RELATIVE_PATH REL_DIR ${PROJECT_SOURCE_DIR}/${baseDir}
         ${CMAKE_CURRENT_LIST_DIR}
    )
    string(REPLACE "/" ";" DIR_LIST ${REL_DIR})
    set(${outList} ${DIR_LIST} PARENT_SCOPE)
endfunction()

# Removes -fuse-ld=lld from target link options to avoid stripping PyInit symbols
function(ogs_remove_lld_linker_option target)
    # lld linker strips out PyInit_OpenGeoSys symbol. Use standard linker.
    get_target_property(_link_options ${target} LINK_OPTIONS)
    if(_link_options)
        list(REMOVE_ITEM _link_options -fuse-ld=lld)
        set_target_properties(${target} PROPERTIES LINK_OPTIONS "${_link_options}")
    endif()
endfunction()
