.load_vs_env: &load_vs_env
  - |
    pushd $env:VS170COMNTOOLS
    cmd /c "VsDevCmd.bat -arch=amd64 -host_arch=amd64&set" |
    foreach {
      if ($_ -match "=") {
        $v = $_.split("=", 2); set-item -force -path "ENV:\$($v[0])"  -value "$($v[1])"
      }
    }
    popd
    Write-Host "`nVisual Studio Command Prompt variables set." -ForegroundColor Yellow

.vs-environment:
  before_script:
    - *load_vs_env

.vs-mkl-environment:
  before_script:
    - *load_vs_env
    # Load MKL environment
    - '& "C:\Program Files (x86)\Intel\oneAPI\compiler\2022.1.0\env\vars.bat"'
    - '& "C:\Program Files (x86)\Intel\oneAPI\mkl\2022.1.0\env\vars.bat"'
    - $env:PATH += ";C:\Program Files (x86)\Intel\oneAPI\compiler\2022.1.0\windows\redist\intel64_win\compiler"
