format:
  tab_size: 4
  max_subgroups_hwrap: 3
  dangle_parens: true
  command_case: "unchanged"
  line_width: 80
lint:
  disabled_codes:
    - "C0301"
    - "C0301" # Line to long.
    - "C0113" # Missing COMMAND for optional dependencies.

parse:
  vartags:
    - !!python/tuple
      - set_property
      - - cmdline
  additional_commands:
    ogs_add_library:
      pargs:
        nargs: 2+
    addtest:
      pargs:
        nargs: "*"
        flags:
          - DISABLED
      spelling: AddTest
      kwargs:
        EXECUTABLE: 1
        PATH: 1
        NAME: 1
        WRAPPER: 1
        TESTER: 1
        ABSTOL: 1
        RELTOL: 1
        RUNTIME: 1
        DEPENDS: 1
        WORKING_DIRECTORY: 1
        EXECUTABLE_ARGS: +
        DATA: +
        DIFF_DATA:
          pargs:
            tags:
              - cmdline
        WRAPPER_ARGS: +
        REQUIREMENTS: +
        PYTHON_PACKAGES: +

    ogstest:
      pargs:
        nargs: "*"
        flags:
          - DISABLED
      spelling: OgsTest
      kwargs:
        PROJECTFILE: 1
        RUNTIME: 1
        WRAPPER: +

    cpmaddpackage:
      pargs:
        nargs: "*"
        flags: []
      spelling: CPMAddPackage
      kwargs: &cpmaddpackagekwargs
        NAME: 1
        FORCE: 1
        VERSION: 1
        GIT_TAG: 1
        DOWNLOAD_ONLY: 1
        GITHUB_REPOSITORY: 1
        GITLAB_REPOSITORY: 1
        GIT_REPOSITORY: 1
        SVN_REPOSITORY: 1
        SVN_REVISION: 1
        SOURCE_DIR: 1
        DOWNLOAD_COMMAND: 1
        FIND_PACKAGE_ARGUMENTS: 1
        NO_CACHE: 1
        GIT_SHALLOW: 1
        URL: 1
        URL_HASH: 1
        URL_MD5: 1
        DOWNLOAD_NAME: 1
        DOWNLOAD_NO_EXTRACT: 1
        HTTP_USERNAME: 1
        HTTP_PASSWORD: 1
        EXCLUDE_FROM_ALL: 1
        OPTIONS: +
        PATCH_COMMAND: +
    cpmfindpackage:
      pargs:
        nargs: "*"
        flags: []
      spelling: CPMFindPackage
      kwargs: *cpmaddpackagekwargs
    cpmdeclarepackage:
      pargs:
        nargs: "*"
        flags: []
      spelling: CPMDeclarePackage
      kwargs: *cpmaddpackagekwargs
    packageproject:
      pargs:
        nargs: "*"
        flags: []
      spelling: packageProject
      kwargs:
        NAME: 1
        VERSION: 1
        INCLUDE_DIR: 1
        INCLUDE_DESTINATION: 1
        BINARY_DIR: 1
        COMPATIBILITY: 1
        VERSION_HEADER: 1
        DEPENDENCIES: +
    cpmusepackagelock:
      pargs: 1
      spelling: CPMUsePackageLock
    cpmregisterpackage:
      pargs: 1
      spelling: CPMRegisterPackage
    cpmgetpackageversion:
      pargs: 2
      spelling: CPMGetPackageVersion

    buildexternalproject:
      pargs:
        nargs: "*"
      spelling: BuildExternalProject
      kwargs:
        GIT_REPOSITORY: 1
        GIT_TAG: 1
        CONFIGURE_COMMAND: +
        BUILD_COMMAND: +
        INSTALL_COMMAND: +
        BUILD_IN_SOURCE: 1
        LOG_OUTPUT_ON_FAILURE: 1
        CMAKE_ARGS: +
