# Vale configuration file.
#
# For more information, see https://vale.sh/docs/topics/config
StylesPath = Documentation/.vale
Vocab = ogs
MinAlertLevel = suggestion
IgnoredScopes = text.frontmatter, code, tt

[*.md]
BasedOnStyles = Vale, write-good, ogs
Vale.Spelling = None
write-good.ThereIs = None
write-good.Passive = None
write-good.TooWordy = None
write-good.Weasel = None
write-good.E-Prime = None

TokenIgnores = \
(\{\{[^}]*\}\}), \
(.*?\{\{[%<]?/.*[%>]\}\}), \
({{[%<] .* [%>]}}.*?{{[%<] ?/.* [%>]}}), \
(\[.+\]\({{< .+ >}}\)), \
[^\S\r\n]({{[%<] \w+ .+ [%>]}})\s, \
[^\S\r\n]({{[%<](?:/\*) .* (?:\*/)[%>]}})\s, \
(\\(?:ref|subpage|copydoc)\s+\S+(?:\s+"[^"]*")?), \
; (\\copydoc\s\S*), \
(\$[^\n$]+\$), \
(\\\S*|\{\S*\}), \
(\w*\set\sal), \
({{<\s?(rel)?ref (.*)>}})

# https://regex101.com/r/QWLhgT/1 helped me generating this one:
BlockIgnores = (?s) *(\$\$.*?\$\$), \
(?sm)^({{[%<] \w+ [^{]*?\s[%>]}})\n$, \
(?s) *({{< highlight [^>]* ?>}}.*?{{< ?/ ?highlight >}}), \
(?s) *(\\f\[.*?\\f\]), \
(\[[^]\n]*\]\(https?://[^)\n]+\)), \
(?s)(\{\{<.*?>\}\}), \
(`+[^`\n]+`+)
