FROM python:3-slim
RUN pip install LinkChecker==10.2.1
CMD [ "/bin/bash" ]
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    --no-install-recommends curl git gnupg2 && \
    rm -rf /var/lib/apt/lists/*
RUN apt -y install curl dirmngr apt-transport-https ca-certificates \
    && curl -sL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get -y install nodejs npm \
    && rm -rf /var/lib/apt/lists/*
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y yarn \
    && rm -rf /var/lib/apt/lists/*
RUN yarn global add node-gyp
RUN yarn global add netlify-cli@16.9.3
ENV HUGO_VERSION=0.117.0
RUN curl -fSL -O "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb" \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y /hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
    && rm /hugo_extended_${HUGO_VERSION}_linux-amd64.deb
RUN pip install nbconvert
