FROM python:3-slim
RUN pip install LinkChecker==10.1.0
CMD [ "/bin/bash" ]
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    --no-install-recommends curl git gnupg2 && \
    rm -rf /var/lib/apt/lists/*
RUN apt -y install curl dirmngr apt-transport-https ca-certificates \
    && curl -sL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get -y install nodejs npm \
    && rm -rf /var/lib/apt/lists/*
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y yarn \
    && rm -rf /var/lib/apt/lists/*
RUN yarn global add node-gyp
RUN yarn global add netlify-cli
ENV HUGO_VERSION=0.101.0
RUN curl -fSL -O "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb" \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y /hugo_extended_${HUGO_VERSION}_Linux-64bit.deb \
    && rm /hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
RUN pip install https://github.com/bilke/nb2hugo/archive/0930c6591a4dae07c794b797a264fbcac1ad91aa.zip
