FROM ubuntu:21.04

ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update \
    && apt-get install -y --no-install-recommends git gcc g++ python3-pip clang-format-12 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install pre-commit==2.13.0
