#### Packaging setup ####
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "OGS-6 THM/C Simulator")
SET(CPACK_PACKAGE_VENDOR "OpenGeoSys Community (http://www.opengeosys.org)")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "OGS-${OGS_VERSION_MAJOR}.${OGS_VERSION_MINOR}.${OGS_VERSION_PATCH}")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_SOURCE_DIR}/README.md")
SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE.txt")
SET(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README.md")
# SET(CPACK_RESOURCE_FILE_WELCOME "${CMAKE_SOURCE_DIR}/README.md")
SET(CPACK_PACKAGE_VERSION_MAJOR "${OGS_VERSION_MAJOR}")
SET(CPACK_PACKAGE_VERSION_MINOR "${OGS_VERSION_MINOR}")
SET(CPACK_PACKAGE_VERSION_PATCH "${OGS_VERSION_PATCH}")
SET(CPACK_PACKAGE_FILE_NAME "ogs-${OGS_VERSION}-${CMAKE_SYSTEM}-x${BITS}")
SET(CPACK_PACKAGE_ICON ${CMAKE_SOURCE_DIR}/Documentation/OpenGeoSys-Logo.png)
#SET(CPACK_COMPONENTS_ALL_IN_ONE_PACKAGE 1)

IF (WIN32)
	INCLUDE (packaging/PackagingWin)
ENDIF()
IF(UNIX)
	INCLUDE (packaging/PackagingLinux)
ENDIF()
IF(APPLE)
	INCLUDE (packaging/PackagingMac)
ENDIF()

# Additional binaries, i.e. OGS-5 file converter
# Can be given as a list, paths must be relative to CMAKE_BINARY_DIR!
IF(OGS_PACKAGE_ADDITIONAL_BINARIES)
	FOREACH(ADDITIONAL_BINARY ${OGS_PACKAGE_ADDITIONAL_BINARIES})
		GET_FILENAME_COMPONENT(ADDITIONAL_BINARY_NAME ${ADDITIONAL_BINARY} NAME)
		MESSAGE(STATUS "Packaging additional binary: ${ADDITIONAL_BINARY_NAME}")
		IF(APPLE AND OGS_BUILD_GUI)
			SET(INSTALL_LOCATION DataExplorer.app/Contents/MacOS)
		ELSE()
			SET(INSTALL_LOCATION bin)
		ENDIF()
		INSTALL (PROGRAMS ${CMAKE_BINARY_DIR}/${ADDITIONAL_BINARY} DESTINATION ${INSTALL_LOCATION} COMPONENT ogs_extras)
	ENDFOREACH()
ENDIF()

INCLUDE (CPack)

cpack_add_component_group(Applications
	DISPLAY_NAME Applications
	DESCRIPTION "OpenGeoSys applications"
	EXPANDED
	BOLD_TITLE
)

cpack_add_component_group(Utilities
	DISPLAY_NAME Utilities
	DESCRIPTION "OpenGeoSys utilities"
	EXPANDED
)

cpack_add_component(ogs_extras
	DISPLAY_NAME "Extra tools"
	DESCRIPTION "Miscellaneous tools."
	GROUP Utilities
)
