# From http://www.cmake.org/pipermail/cmake/2012-September/052098.html
macro(ConfigureMacOSXBundle TARGET_NAME ICON_FILE_PATH)

	get_filename_component(ICON_FILE_NAME "${ICON_FILE_PATH}" NAME)

	set_target_properties(${TARGET_NAME} PROPERTIES
		MACOSX_BUNDLE_INFO_STRING "${PROJECT_NAME} ${OGS_VERSION} - ${TARGET_NAME}"
		MACOSX_BUNDLE_ICON_FILE ${ICON_FILE_NAME}
		MACOSX_BUNDLE_GUI_IDENTIFIER "org.opengeosys"
		MACOSX_BUNDLE_BUNDLE_NAME ${PROJECT_NAME}-${TARGET_NAME}
		MACOSX_BUNDLE_SHORT_VERSION_STRING ${OGS_VERSION}
		MACOSX_BUNDLE_LONG_VERSION_STRING "${PROJECT_NAME} ${OGS_VERSION}"
		MACOSX_BUNDLE_BUNDLE_VERSION ${OGS_VERSION}
		MACOSX_BUNDLE_COPYRIGHT "Copyright 2015, OpenGeoSys Community. All Rights Reserved."
	)

	SET_SOURCE_FILES_PROPERTIES(${ICON_FILE_PATH} PROPERTIES
		MACOSX_PACKAGE_LOCATION Resources)
endmacro()
