stages:
  - build
  - release
  - test

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        PYPI_REPO: --repository pypi
        PYPI_USER: __token__
        PYPI_PW: "${PYPI_TOKEN}"
        GIT_DEPTH: 1000
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        PYPI_REPO: --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
        PYPI_USER: gitlab-ci-token
        PYPI_PW: "${CI_JOB_TOKEN}"
        SETUPTOOLS_SCM_LOCAL_SCHEME: no-local-version
        GIT_DEPTH: 1000
    - if: $CI_MERGE_REQUEST_ID
      variables:
        CIBW_BUILD: cp310*
        GIT_DEPTH: 1000

include:
  - local: "scripts/ci/extends/*.yml"

.wheels_template: &wheels_template
  stage: build
  script:
    - uvx cibuildwheel
  rules:
    - if: $CI_MERGE_REQUEST_LABELS =~ /.*ci::wheels only.*/
      variables:
        CIBW_BUILD: cp310*
        GIT_DEPTH: 1000
    - when: on_success
  artifacts:
    paths:
      - wheelhouse/

build wheels linux:
  tags: [envinf, shell, fast]
  variables:
    CPM_SOURCE_CACHE: /host/cibuildwheel_cache/cpm
    CCACHE_DIR: /host/cibuildwheel_cache/ccache
    CCACHE_MAXSIZE: 15G
  <<: *wheels_template

build wheels mac:
  tags: [mac, arm64]
  variables:
    CMAKE_OSX_DEPLOYMENT_TARGET: "10.15"
  <<: *wheels_template

build wheels win:
  tags: [windows]
  extends:
    - .vs-environment
  variables:
    SKBUILD_BUILD_OPTIONS: "/m" # TODO not supported yet in scikit-build-core
  timeout: 10h
  <<: *wheels_template

publish wheels:
  stage: release
  needs: ["build wheels linux", "build wheels mac", "build wheels win"]
  tags: [envinf, shell]
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - when: never
  script:
    - uvx --from build pyproject-build --sdist --outdir wheelhouse
    - >
      uvx twine upload
      ${PYPI_REPO}
      --username ${PYPI_USER} --password ${PYPI_PW}
      wheelhouse/*

publish wheels to pypi (dev):
  stage: release
  needs: ["build wheels linux", "build wheels mac"] # , "build wheels win", # disabled temporarily due to runner hardware failure
  tags: [envinf, shell]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: manual
  script:
    - uvx --from build pyproject-build --sdist --outdir wheelhouse
    - >
      uvx twine upload --repository pypi
      --username __token__ --password ${PYPI_TOKEN}
      wheelhouse/*
