meta:
  stage: .pre
  tags: [shell]
  variables:
    GIT_DEPTH: 1000
  script:
    - echo "OGS_VERSION=${CI_COMMIT_TAG:-`git describe --tags --long --dirty --always`}" >> build.env
    - cat build.env
  artifacts:
    reports:
      dotenv: build.env
