aggregate ctest logs:
  stage: package
  tags: [envinf, shell]
  script:
    - |
      out_root=build/log_summary
      python -m venv .venv_custom_job
      . .venv_custom_job/bin/activate
      pip install pandas
      mkdir -p build/log_summary
      set -x
      Applications/Python/ogs/dev/ogs_log_summary.py --snippet-out --out "$out_root" -v build/*/logs &>"$out_root/ogs_log_summary.txt"
      #
      # summarize failed ctests
      #
      function exists() {
        [ -e "$1" ]
      }
      if exists build/*/Testing/Temporary/LastTestsFailed*.log
      then
        out_dir="$out_root/Testing/Temporary"
        mkdir -p "$out_dir"
        echo "### Failed ctests from all jobs (and number of jobs where they failed):"
        cut -d':' -f2- build/*/Testing/Temporary/LastTestsFailed*.log | sort | uniq -c | tee "$out_dir/LastTestsFailed.log"
      fi
  rules:
    - when: always
  artifacts:
    name: all-artifacts
    paths:
      - "build/**/*.txt"
      - "build/log_summary/**"
    expire_in: 12 hrs

cleanup_packages:
  image: python:3.12
  stage: package
  needs: []
  script:
    - pip install requests
    - python3 scripts/ci/helper/cleanup_packages.py
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  variables:
    GITLAB_TOKEN: $REPO_WRITE_KEY
    KEEP_PACKAGE_VERSIONS: "5"   # keep newest 5 versions
