if (NOT OGS_USE_MPI)
    OgsTest(PROJECTFILE LIE/Mechanics/cohesive_zone_load_path.prj RUNTIME 2)
    OgsTest(PROJECTFILE LIE/Mechanics/coulomb_load_path.prj RUNTIME 2)
    OgsTest(PROJECTFILE LIE/Mechanics/elastic_push_pull_two_fractures.prj RUNTIME 1)
    OgsTest(PROJECTFILE LIE/Mechanics/mohr_coulomb_load_path_nu0p3.prj RUNTIME 15)
    OgsTest(PROJECTFILE LIE/Mechanics/single_joint_3D.prj)
    OgsTest(PROJECTFILE LIE/Mechanics/single_joint.prj)
    OgsTest(PROJECTFILE LIE/Mechanics/single_joint_inside.prj)
    OgsTest(PROJECTFILE LIE/Mechanics/two_joints.prj)
    OgsTest(PROJECTFILE LIE/Mechanics/single_joint_negative_aperture.prj)
    OgsTest(PROJECTFILE LIE/Mechanics/single_joint_displacement_controlled.prj)
    OgsTest(PROJECTFILE LIE/Mechanics/two_cracks_branch_pull.prj)
    OgsTest(PROJECTFILE LIE/Mechanics/two_cracks_junction_pull.prj)
    OgsTest(PROJECTFILE LIE/Mechanics/sfrac.q.prj)
    OgsTest(PROJECTFILE LIE/Mechanics/GreatCellWithBBar/mechanics_embedded_fracture_F.prj)
endif()
