from __future__ import annotations

import sys
from pathlib import Path

sys.path.append(str(Path("Applications").joinpath("Python").absolute()))
from ogs._internal.binaries_list import get_binaries_list


def pyproject_get_binaries():
    # config.py is generated by CMake and may not exist yet during the
    # editable-install metadata phase; fall back to the default in that case.
    try:
        from ogs.config import OGS_USE_PETSC  # noqa: PLC0415
    except ImportError:
        OGS_USE_PETSC = "OFF"
    return {
        binary: f"ogs._internal.provide_ogs_cli_tools_via_wheel:{binary}"
        for binary in get_binaries_list(OGS_USE_PETSC)
    }


__all__ = ["dynamic_metadata"]


def __dir__() -> list[str]:
    return __all__


def dynamic_metadata(
    field: str,
    settings: dict[str, object] | None = None,
) -> str:
    if field != "scripts":
        msg = "Only the 'scripts' field is supported"
        raise ValueError(msg)

    if settings:
        msg = "No inline configuration is supported"
        raise ValueError(msg)

    return pyproject_get_binaries()
