if (NOT OGS_USE_MPI)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/coarse/bar.prj")
    # same as bar/coarse but with tangent type being Elastic.
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/coarse_elastic_tangent/bar.prj" LARGE)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/medium/bar.prj")
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/fine/bar.prj" LARGE)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/veryfine/bar.prj" LARGE)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/p1/bar.prj")
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/p2/bar.prj")
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/p3/bar.prj")
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/t1/bar.prj" RUNTIME 14)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/t2/bar.prj")
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/beam/coarse/beam.prj")
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/beam/medium/beam.prj" RUNTIME 38)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/beam/fine/beam.prj" LARGE)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/beam/coarse_quad/beam.prj" RUNTIME 27)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/beam/coarse_tria/beam.prj" RUNTIME 12)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/beam/3D_hexa/beam.prj" LARGE)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/beam/3D_tetr/beam.prj" LARGE)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/holed_beam/holed_beam.prj" LARGE)
endif() # OGS_USE_MPI
