if (NOT OGS_USE_MPI)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/coarse/bar.prj")
    # same as bar/coarse but with tangent type being Elastic.
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/coarse_elastic_tangent/bar.prj" RUNTIME 145)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/medium/bar.prj" RUNTIME 7)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/fine/bar.prj" RUNTIME 65)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/veryfine/bar.prj" RUNTIME 365)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/p1/bar.prj")
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/p2/bar.prj")
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/p3/bar.prj")
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/t1/bar.prj" RUNTIME 14)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/bar/t2/bar.prj" RUNTIME 35)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/beam/coarse/beam.prj" RUNTIME 7)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/beam/medium/beam.prj" RUNTIME 38)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/beam/fine/beam.prj" RUNTIME 441)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/beam/coarse_quad/beam.prj" RUNTIME 27)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/beam/coarse_tria/beam.prj" RUNTIME 12)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/beam/3D_hexa/beam.prj" RUNTIME 105)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/beam/3D_tetr/beam.prj" RUNTIME 134)
    OgsTest(PROJECTFILE "Mechanics/EhlersDamageNonLocal/holed_beam/holed_beam.prj" RUNTIME 247)
endif() # OGS_USE_MPI
