#ifndef PROCESSLIB_TES_FEM_DATA_IMPL_INCL
#define PROCESSLIB_TES_FEM_DATA_IMPL_INCL

static_assert(OGS_EIGEN_DYNAMIC_SHAPE_MATRICES_FLAG == 1, "inconsistent use of macros");

#endif // PROCESSLIB_TES_FEM_DATA_IMPL_INCL
