import sys


def get_binaries_list(ogs_use_petsc="OFF"):
    result = [
        "addDataToRaster",
        "AddElementQuality",
        "AddFaultToVoxelGrid",
        "AddLayer",
        "appendLinesAlongPolyline",
        "AssignRasterDataToMesh",
        "checkMesh",
        "ComputeNodeAreasFromSurfaceMesh",
        "computeSurfaceNodeIDsInPolygonalRegion",
        "constructMeshesFromGeometry",
        "convertGEO",
        "convertToLinearMesh",
        "convertVtkDataArrayToVtkDataArray",
        "CreateAnchors",
        "CreateBoundaryConditionsAlongPolylines",
        "createIntermediateRasters",
        "createLayeredMeshFromRasters",
        "createMeshElemPropertiesFromASCRaster",
        "createNeumannBc",
        "createQuadraticMesh",
        "createRaster",
        "createTetgenSmeshFromRasters",
        "editMaterialID",
        "ExtractBoundary",
        "ExtractMaterials",
        "ExtractSurface",
        "Feflow2Mesh",
        "generateGeometry",
        "generateMatPropsFromMatID",
        "generateStructuredMesh",
        "geometryToGmshGeo",
        "GMSH2OGS",
        "GocadSGridReader",
        "GocadTSurfaceReader",
        "identifySubdomains",
        "IntegrateBoreholesIntoMesh",
        "ipDataToPointCloud",
        "Layers2Grid",
        "MapGeometryToMeshSurface",
        "mergeMeshToBulkMesh",
        "Mesh2Raster",
        "MeshMapping",
        "MoveGeometry",
        "MoveMesh",
        "moveMeshNodes",
        "mpmetis",
        "NodeReordering",
        "ogs",
        "OGS2VTK",
        "partmesh",
        "postLIE",
        "PVD2XDMF",
        "pvtu2vtu",
        "queryMesh",
        "Raster2ASC",
        "Raster2Mesh",
        "RemoveGhostData",
        "removeMeshElements",
        "RemoveUnusedPoints",
        "ReorderMesh",
        "ResetPropertiesInPolygonalRegion",
        "reviseMesh",
        "scaleProperty",
        "swapNodeCoordinateAxes",
        "TecPlotTools",
        "TIN2VTK",
        "VTK2OGS",
        "VTK2TIN",
        "vtkdiff",
        "Vtu2Grid",
        "xdmfdiff",
    ]

    if ogs_use_petsc == "ON":
        result.append("binaryToPVTU")

    if sys.platform != "win32":
        result.append("apply_xmlpatch")

    return result
