OgsTest(PROJECTFILE WellboreSimulator/1Phase_wellbore_small_newton.prj RUNTIME 1)
OgsTest(PROJECTFILE WellboreSimulator/2Phase_wellbore_small_newton.prj RUNTIME 4)
OgsTest(PROJECTFILE WellboreSimulator/2Phase_wellbore_small_newton_nonnegdamping.prj RUNTIME 3)

