#message("tester: ${TESTER_COMMAND}")
#STRING(REPLACE " " ";" TESTER_COMMAND ${TESTER_COMMAND})
#set(list ${TESTER_COMMAND})
#message("tester: ${list}")


EXECUTE_PROCESS(
	COMMAND bash -c ${TESTER_COMMAND}
	WORKING_DIRECTORY ${case_path}
	RESULT_VARIABLE EXIT_CODE
)

IF(NOT EXIT_CODE STREQUAL "0")
	MESSAGE(FATAL_ERROR "Error exit code: ${EXIT_CODE}")
ENDIF()
