if (NOT OGS_USE_MPI)
    OgsTest(PROJECTFILE LargeDeformation/RigidBody/square_1e0.prj RUNTIME 1)
    if(OGS_BUILD_PROCESS_SmallDeformation)
        NotebookTest(NOTEBOOKFILE LargeDeformation/RigidBody/RigidBody.py RUNTIME 7)
    endif()
    OgsTest(PROJECTFILE LargeDeformation/Torsion/bar1to6_torsion.prj RUNTIME 5)
    NotebookTest(NOTEBOOKFILE LargeDeformation/Torsion/Torsion_robustness.py RUNTIME 9)

    OgsTest(PROJECTFILE LargeDeformation/CooksMembrane/CooksMembrane.prj RUNTIME 1)
    OgsTest(PROJECTFILE LargeDeformation/CooksMembrane/CooksMembraneLDRefinedMesh10.xml RUNTIME 1)
    OgsTest(PROJECTFILE LargeDeformation/CooksMembrane/CooksMembraneLDRefinedMesh15.xml RUNTIME 1)
    OgsTest(PROJECTFILE LargeDeformation/CooksMembrane/CooksMembraneLDRefinedMesh20.xml RUNTIME 2)
    OgsTest(PROJECTFILE LargeDeformation/CooksMembrane/CooksMembraneLDRefinedMesh25.xml RUNTIME 2)
    OgsTest(PROJECTFILE LargeDeformation/CooksMembrane/CooksMembraneLDRefinedMesh30.xml RUNTIME 4)
    OgsTest(PROJECTFILE LargeDeformation/CooksMembrane/3D/CooksMembraneLD_3D.prj RUNTIME 4)
    OgsTest(PROJECTFILE LargeDeformation/RubberIndentation/RubberIndentation.prj RUNTIME 1)
    OgsTest(PROJECTFILE LargeDeformation/Indentation3D/Indentation3D.prj RUNTIME 10)
    OgsTest(PROJECTFILE LargeDeformation/ThickCylindricalShell/ThickCylindricalShell.prj RUNTIME 5)

    NotebookTest(NOTEBOOKFILE LargeDeformation/CooksMembrane/CooksMembraneFbar.py RUNTIME 13)
    NotebookTest(NOTEBOOKFILE LargeDeformation/FbarBenchmarksLocking.py RUNTIME 31)
endif()
