if (NOT OGS_USE_MPI)
    OgsTest(PROJECTFILE LargeDeformation/RigidBody/square_1e0.prj RUNTIME 1)
    if(OGS_BUILD_PROCESS_SmallDeformation)
        NotebookTest(NOTEBOOKFILE LargeDeformation/RigidBody/RigidBody.py RUNTIME 15)
    endif()
    OgsTest(PROJECTFILE LargeDeformation/Torsion/bar1to6_torsion.prj RUNTIME 5)
    NotebookTest(NOTEBOOKFILE LargeDeformation/Torsion/Torsion_robustness.py RUNTIME 15)

    OgsTest(PROJECTFILE LargeDeformation/CooksMembrane/CooksMembrane.prj RUNTIME 4)
    OgsTest(PROJECTFILE LargeDeformation/CooksMembrane/CooksMembraneLDRefinedMesh10.xml RUNTIME 4)
    OgsTest(PROJECTFILE LargeDeformation/CooksMembrane/CooksMembraneLDRefinedMesh15.xml RUNTIME 4)
    OgsTest(PROJECTFILE LargeDeformation/CooksMembrane/CooksMembraneLDRefinedMesh20.xml RUNTIME 2)
    OgsTest(PROJECTFILE LargeDeformation/CooksMembrane/CooksMembraneLDRefinedMesh25.xml RUNTIME 2)
    OgsTest(PROJECTFILE LargeDeformation/CooksMembrane/CooksMembraneLDRefinedMesh30.xml RUNTIME 4)
    OgsTest(PROJECTFILE LargeDeformation/CooksMembrane/3D/CooksMembraneLD_3D.prj RUNTIME 4)
endif()

