include = [
  "^https://gitlab\\.opengeosys\\.org",
  "^https://discourse\\.opengeosys\\.org",
]
exclude = [".*"]
exclude_path = [
  "public/index.html",
  "public/docs/devguide/development-workflows/setup-fork/index.html",
  ".*ogs/ogs/-/jobs/artifacts/master/browse/build.*",
]
